version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - pip install -e .
      - pip install sphinx==4.0.0 pydata-sphinx-theme==0.13.3 sphinx-autodoc-typehints sphinx-copybutton

sphinx:
  configuration: docs/conf.py