version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - pip install -e .
      - pip install sphinx==7.1.2 pydata-sphinx-theme==0.14.4 sphinx-autodoc-typehints sphinx-copybutton myst-parser snowballstemmer

sphinx:
  configuration: docs/conf.py